# Generated by Django 5.1.6 on 2025-03-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prescription'),
        ),
    ]
