# Generated by Django 5.1.6 on 2025-04-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionmedicine',
            old_name='quantity',
            new_name='duration',
        ),
    ]
