# Generated by Django 5.1.6 on 2025-04-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_quantity_prescriptionmedicine_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
