# Generated by Django 5.1.6 on 2025-03-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='status',
            new_name='blood_group',
        ),
    ]
