# Generated by Django 5.1.6 on 2025-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_prescriptionmedicine_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
