# Generated by Django 5.1.6 on 2025-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_department_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='requires_prescription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='requires_prescription',
            field=models.BooleanField(default=True),
        ),
    ]
