# Generated by Django 5.1.6 on 2025-03-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_prescription_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories', to='api.prescription'),
        ),
    ]
