# Generated by Django 5.1.6 on 2025-04-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_labtest_requires_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='prescription',
        ),
    ]
