# Generated by Django 5.1.6 on 2025-04-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bill_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='api.bill')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='api.bill')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
        ),
    ]
