# Generated by Django 5.1.6 on 2025-04-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_labtestbillitem_medicinebillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(default='Mark Twain', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
