# Generated by Django 5.1.6 on 2025-04-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bill_name_bill_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionlabtest',
            name='test_date',
        ),
    ]
