# Generated by Django 5.1.6 on 2025-04-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('requested_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.labtechnician')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='LabReportTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField()),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labreport')),
                ('prescription_lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescriptionlabtest')),
            ],
        ),
    ]
